native_amd64_task:
  matrix:
  - name: x86_64
    compute_engine_instance:
      image_project: ubuntu-os-cloud
      image: ubuntu-2404-noble-amd64-v20240423
      platform: linux
      architecture: amd64
  - name: ARM
    compute_engine_instance:
      image_project: ubuntu-os-cloud
      image: ubuntu-2404-noble-arm64-v20240423
      platform: linux
      architecture: arm64
  script:
    - uname -a
    - curl -s https://repos.azul.com/azul-repo.key | gpg --dearmor -o /usr/share/keyrings/azul.gpg
    - echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" | tee /etc/apt/sources.list.d/zulu.list
    - apt-get update && apt-get install -y build-essential clang zulu22-jdk
    - git clone https://github.com/axboe/liburing.git && cd liburing && ./configure && make && sudo make install && cd ..
    - wget -q https://github.com/sbt/sbt/releases/download/v1.10.0/sbt-1.10.0.tgz && tar xvfz sbt-1.10.0.tgz
    - sbt/bin/sbt test
